# Generated by Django 4.2 on 2025-05-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='favorite',
        ),
    ]
