# Generated by Django 4.2 on 2025-04-19 04:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_song_language_remove_song_lyrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
