# Generated by Django 4.2 on 2025-04-19 08:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_download_id_alter_favorite_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_image_url',
        ),
        migrations.AddField(
            model_name='album',
            name='thumbnail_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
