# Generated by Django 4.2 on 2025-04-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_remove_album_cover_image_url_album_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='song',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='media.song'),
        ),
    ]
