# Generated by Django 4.2 on 2025-04-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_alter_album_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='song',
        ),
        migrations.AddField(
            model_name='album',
            name='song',
            field=models.ManyToManyField(blank=True, null=True, related_name='albums', to='media.song'),
        ),
    ]
