# Generated by Django 4.2 on 2025-04-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_remove_album_song_album_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='song',
            field=models.ManyToManyField(blank=True, related_name='albums', to='media.song'),
        ),
    ]
