# Generated by Django 4.2 on 2025-04-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_alter_album_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='song',
            new_name='songs',
        ),
    ]
